=== marrerom/APONE/IREPServices/resources/schemas/experiment_schema.json
{
"$schema" : "http://json-schema.org/schema#",

"title" : "Experiment schema",

"description" : "Data related to the definition of an experiment",

"type" : "object",

"properties" : 
	{
	"_id": {"type":"string"},
	"name": {"type":"string"},
	"experimenter": {"type":"string"},
	"description": {"type":"string"},
	"unit": {"type":"string"},
	"treatment" : {"type":"array", "items": {"$ref": "#/definitions/treatItem" } },
	"config" : {"type":"array", "items": {"$ref": "#/definitions/configItem" } }
	},

"definitions": {
    "treatItem": 
    	{
		"type" : "object",
		"properties" : 
			{
			"name":{"type":"string"},
			"description": {"type":"string"},
			"definition": {"type":"string"},
			"iscontrol":{"type":"boolean"}
			}
		},
	"configItem":
		{
		"type" : "object",
		"properties": 
			{
			"_id": {"type":"string"},
			"name": {"type":"string"},
			"experimenter": {"type":"string"},
			"description": {"type":"string"},
			"controller_code": {"type":"string"},
			"date_started": {"type": "array", "items":{"type":"string"}},
			"date_ended": {"type": "array", "items":{"type":"string"}},
			"run":{"enum":["ON","OFF","PAUSED"], "default":"OFF"},
			"date_to_end": {"type": "string"},
			"max_exposures": {"type": "number"},
			"test":{"type":"boolean"},
			"dist": {"type":"array", "items": {"$ref": "#/definitions/distItem" } } 
			}
		},
	"distItem": 
		{
		"type" : "object",
		"properties" : 
			{
			"segments":{"type":"number"},
			"treatment": {"type":"string"},
			"action": {"enum":["ADD","REMOVE"], "default":"add"}
			}

		}
  }
}

=== marrerom/APONE/WebContent/WEB-INF/demoAP.json
{
    "name" : "AveragePrecision", 
    "experimenter" : "ANONYMOUS", 
    "description" : "Experiment to reproduce partially the work described in: A. Turpin and F. Scholer, 'User Performance versus Precision Measures for Simple Search Tasks', 2006. The users are exposed to a topic (randomly selected) and a SERP with predefined levels of AP (55, 75 or 95). The time to find the first relevant result is registered, as well as the percentage of relevant documents found and the percentage of non relevants checked as relevants.", 
    "unit" : "defaultunit", 
    "treatment" : [
        {
            "name" : "55", 
            "description" : "AP=55", 
            "control" : true, 
            "url" : "http://ireplatform.ewi.tudelft.nl:8080/ClientAP"
        }, 
        {
            "name" : "75", 
            "description" : "AP=75", 
            "control" : true, 
            "url" : "http://ireplatform.ewi.tudelft.nl:8080/ClientAP"
        },
        {
            "name" : "95", 
            "description" : "AP=95", 
            "control" : true, 
            "url" : "http://ireplatform.ewi.tudelft.nl:8080/ClientAP"
        }
        
    ], 
    "config" : [
        {
            "name" : "test", 
            "experimenter" : "ANONYMOUS", 
            "distribution" : [
                {
                    "segments" : 33, 
                    "treatment" : "55", 
                    "action" : "ADD"
                }, 
                {
                    "segments" : 33, 
                    "treatment" : "75", 
                    "action" : "ADD"
                },
                {
                    "segments" : 33, 
                    "treatment" : "95", 
                    "action" : "ADD"
                }
            ] 
        }
    ]
}

=== marrerom/APONE/WebContent/WEB-INF/demoFactorial.json
{ 
    "name" : "Ranking+Color", 
    "experimenter" : "ANONYMOUS", 
    "description" : "Experiment to test the effects from the change in the color of the links in the SERP plus the change of the ranking algorithm. Search engine used: ElasticSearch. Link colors: blue, green. Ranking algorithms: ElasticSearch default, BM25. Collection: cran (http://ir.dcs.gla.ac.uk/resources/test_collections/cran/). We will register the SERP pages viewed, the queries issued and the clicks on the resulting documents.", 
    "unit" : "iduser", 
    "treatment" : [
        {
            "name" : "onlyone", 
            "definition" : "linkColor=uniformChoice(choices=['blue','green'], unit=iduser);rankingAlg=uniformChoice(choices=['default','bm25'], unit=iduser);", 
            "control" : true, 
            "url" : "http://ireplatform.ewi.tudelft.nl:8080/ClientColorRanking"
        }
    ], 
    "config" : [
        {
            "name" : "test", 
            "experimenter" : "ANONYMOUS", 
            "controller_code" : "http://ireplatform.ewi.tudelft.nl:8080/ClientColorRanking", 
            "distribution" : [
                {
                    "segments" : 100, 
                    "treatment" : "onlyone", 
                    "action" : "ADD"
                }
            ] 
        }
    ]
}

=== marrerom/APONE/WebContent/WEB-INF/demoColor.json
{
    "name" : "Color", 
    "experimenter" : "ANONYMOUS", 
    "description" : "Experiment to test the change in the color of the links in a SERP. Search engine used: ElasticSearch, ranking algorithm: default, collection: cran (http://ir.dcs.gla.ac.uk/resources/test_collections/cran/). We will register the SERP pages viewed, the queries issued and the clicks on the resulting documents.", 
    "unit" : "defaultunit", 
    "treatment" : [
        {
            "name" : "Blue", 
            "description" : "Link color blue", 
            "control" : true, 
            "url" : "http://ireplatform.ewi.tudelft.nl:8080/ClientColor",
            "definition": "rankingAlg='default';linkColor='blue';"
        }, 
        {
            "name" : "Green", 
            "description" : "Link color green", 
            "control" : false, 
            "url" : "http://ireplatform.ewi.tudelft.nl:8080/ClientColor",
            "definition": "rankingAlg='default';linkColor='green';"
        }
    ], 
    "config" : [
        {
            "name" : "test", 
            "experimenter" : "ANONYMOUS", 
            "distribution" : [
                {
                    "segments" : 50, 
                    "treatment" : "Blue", 
                    "action" : "ADD"
                }, 
                {
                    "segments" : 50, 
                    "treatment" : "Green", 
                    "action" : "ADD"
                }
            ]
        }
    ]
}

=== marrerom/APONE/WebContent/WEB-INF/demoRanking.json
{ 
    "name" : "Ranking", 
    "experimenter" : "ANONYMOUS", 
    "description" : "Experiment to test the change in the color of the links resulting from a search. Search engine used: ElasticSearch, ranking algorithm: default, collection: cran (http://ir.dcs.gla.ac.uk/resources/test_collections/cran/). We will register the SERP pages viewed, the queries issued and the clicks on the resulting documents.", 
    "unit" : "defaultunit", 
    "treatment" : [
        {
            "name" : "Default", 
            "description" : "Default ranking algorithm in ElasticSearch", 
            "control" : true, 
            "url" : "http://ireplatform.ewi.tudelft.nl:8080/ClientE2/index.html?rankingAlg=default&linkColor=blue"
        }, 
        {
            "name" : "BM25", 
            "description" : "BM25 ranking algorithm implemented in ElasticSearch", 
            "control" : false, 
            "url" : "http://ireplatform.ewi.tudelft.nl:8080/ClientE2/index.html?rankingAlg=bm25&linkColor=blue"
        }
    ], 
    "config" : [
        {
            "name" : "test", 
            "experimenter" : "ANONYMOUS", 
            "distribution" : [
                {
                    "segments" : 50, 
                    "treatment" : "Default", 
                    "action" : "ADD"
                }, 
                {
                    "segments" : 50, 
                    "treatment" : "BM25", 
                    "action" : "ADD"
                }
            ]
        }
    ]
}
